using UnityEngine;

public class AudioManager : MonoBehaviour
{
    private static AudioManager _instance;
    public static AudioManager Instance
    {
        get
        {
            if (_instance == null)
            {
                // 씬 내에서 검색
                _instance = FindObjectOfType<AudioManager>();
                
                // 없다면 새로 생성 (Lazy Initialization)
                if (_instance == null)
                {
                    GameObject go = new GameObject("AudioManager (AutoGenerated)");
                    _instance = go.AddComponent<AudioManager>();
                    _instance.InitializeInternal();
                    DontDestroyOnLoad(go);
                }
            }
            return _instance;
        }
    }

    public AudioSource BGMSource;
    public AudioSource SFXSource;

    public bool IsBgmMuted { get; private set; }
    public bool IsSfxMuted { get; private set; }

    private void Awake()
    {
        if (_instance == null)
        {
            _instance = this;
            InitializeInternal();
            DontDestroyOnLoad(gameObject);
        }
        else if (_instance != this)
        {
            Destroy(gameObject);
        }
    }

    private void InitializeInternal()
    {
        // AudioSource 자동 생성 및 강제 초기화
        if (SFXSource == null) SFXSource = gameObject.AddComponent<AudioSource>();
        if (BGMSource == null) BGMSource = gameObject.AddComponent<AudioSource>();

        // [Safety Catch] 뮤트 해제 및 볼륨 확보
        SFXSource.mute = false;
        SFXSource.volume = 1.0f;
        SFXSource.spatialBlend = 0f; // 2D 사운드 강제 (3D 공간감 제거)
        SFXSource.playOnAwake = false;
        BGMSource.mute = false;
        BGMSource.volume = 1.0f;
        BGMSource.spatialBlend = 0f; // 2D 사운드 강제
        BGMSource.playOnAwake = false;

        IsBgmMuted = false;
        IsSfxMuted = false;

        LoadDefaultClips();
    }

    private void LoadDefaultClips()
    {
        // Resources에서 로드 시도
        if (MainBGM == null) MainBGM = Resources.Load<AudioClip>("Audio/BGM/MainBGM");
        if (DropSFX == null) DropSFX = Resources.Load<AudioClip>("Audio/SFX/DropSFX");
        if (MergeSFX == null) MergeSFX = Resources.Load<AudioClip>("Audio/SFX/MergeSFX");
        if (ScoreSFX == null) ScoreSFX = Resources.Load<AudioClip>("Audio/SFX/ScoreSFX");
        if (UIClickSFX == null) UIClickSFX = Resources.Load<AudioClip>("Audio/SFX/UIClickSFX");
        if (GameOverSFX == null) GameOverSFX = Resources.Load<AudioClip>("Audio/SFX/GameOverSFX");

        if (MainBGM != null)
        {
            PlayBGM(MainBGM);
        }

        int loaded = 0;
        if (DropSFX != null) loaded++;
        if (MergeSFX != null) loaded++;
        if (ScoreSFX != null) loaded++;
        if (UIClickSFX != null) loaded++;

        if (loaded >= 4)
            Debug.Log($"[AudioManager] All {loaded} SFX clips loaded.");
        else
            Debug.LogWarning($"[AudioManager] Only {loaded}/4 SFX clips loaded. Missing clips will be silent.");
    }

    // JS -> Unity SendMessage 용
    public void SetBgmMuteFromJS(string muteStr)
    {
        bool mute = muteStr == "1";
        SetBgmMute(mute);
    }

    public void SetSfxMuteFromJS(string muteStr)
    {
        bool mute = muteStr == "1";
        SetSfxMute(mute);
        
        // JS에서 변경된 경우 GameManager의 설정도 업데이트하여 데이터 저장 유도
        if (GameManager.Instance != null)
        {
            GameManager.Instance.UpdateSettings(!mute, GameManager.Instance.IsVibrationEnabled);
        }
    }

    public void SetBgmMute(bool mute)
    {
        IsBgmMuted = mute;
        if (BGMSource != null)
        {
            BGMSource.mute = mute;
            if (!mute && !BGMSource.isPlaying && BGMSource.clip != null)
            {
                BGMSource.Play();
            }
        }
    }

    public void SetSfxMute(bool mute)
    {
        IsSfxMuted = mute;
        if (SFXSource != null)
        {
            SFXSource.mute = mute;
        }
    }

    // 하위 호환성용 (필요 시)
    public void SetMute(bool mute)
    {
        SetBgmMute(mute);
        SetSfxMute(mute);
    }

    public void PlayBGM(AudioClip clip)
    {
        if (BGMSource == null || clip == null) return;
        BGMSource.clip = clip;
        BGMSource.loop = true;
        BGMSource.mute = IsBgmMuted;
        BGMSource.Play();
    }

    [Header("BGM Clips")]
    public AudioClip MainBGM;

    [Header("Game SFX Clips")]
    public AudioClip DropSFX;
    public AudioClip MergeSFX;
    public AudioClip ScoreSFX;
    public AudioClip UIClickSFX;
    public AudioClip GameOverSFX;

    public void PlaySFX(AudioClip clip, float pitchRange = 0.1f)
    {
        if (SFXSource == null || clip == null) return;
        if (IsSfxMuted) return;

        // 매번 살짝 다른 피치를 적용하여 사운드의 단조로움을 피함
        SFXSource.pitch = 1.0f + Random.Range(-pitchRange, pitchRange);
        SFXSource.PlayOneShot(clip);
    }

    // Shortcut methods
    public void PlayDrop() { PlaySFX(DropSFX, 0.05f); }
    public void PlayMerge() { PlaySFX(MergeSFX, 0.08f); }
    public void PlayScore() { PlaySFX(ScoreSFX, 0.12f); }
    public void PlayUIClick() { PlaySFX(UIClickSFX, 0.05f); }
    public void PlayGameOver() { PlaySFX(GameOverSFX); }

    // Handles OS background / foreground
    private void OnApplicationPause(bool pauseStatus)
    {
        if (pauseStatus)
        {
            PauseAllAudio();
        }
        else
        {
            ResumeAllAudio();
        }
    }

    private void OnApplicationFocus(bool hasFocus)
    {
        if (!hasFocus)
        {
            PauseAllAudio();
        }
        else
        {
            ResumeAllAudio();
        }
    }

    private void PauseAllAudio()
    {
        if (BGMSource != null && BGMSource.isPlaying) BGMSource.Pause();
        // Option to pause SFX as well, usually leaving them is fine as they are short, but we pause BGM.
    }

    private void ResumeAllAudio()
    {
        if (BGMSource != null && !IsBgmMuted && !BGMSource.isPlaying)
        {
            if (BGMSource.clip != null)
            {
                BGMSource.UnPause();
                if (!BGMSource.isPlaying) BGMSource.Play();
            }
        }
    }
}
